import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Topbar from "@/components/topbar/topbar";
import Footer from "@/components/footer/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
        <Topbar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
